
name: Release Charts

on:
  push:
    branches:
    - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    # See https://github.com/helm/chart-releaser-action/issues/6
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.0.0-rc.2
      env:
        CR_TOKEN: "${{ secrets.CR_TOKEN }}"
